#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

USE_PROCD=1
START=40
STOP=89
PROG=/usr/bin/opera-proxy

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" -socks-mode -bind-address 127.0.0.1:1080 -verbosity 50
    procd_set_param stdout 1
    procd_set_param stderr 0
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}
